server:
  port: 8080

spring:
  amqp:
    deserialization:
      trust-all: true
  datasource:
    url: jdbc:postgresql://localhost:5432/creditdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      enable-metrics-push: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


kafka:
  topics:
    credit-applications: credit-applications

rabbitmq:
  queues:
    credit-decisions: credit-decisions
flyway:
  enabled: true  # Включить Flyway
  locations: classpath:db/migration  # Путь к вашим миграциям
  baseline-on-migrate: true  # Установить базовую версию, если это необходимо
  clean-on-validation-error: true  # Очистить базу данных при ошибке валидации
