server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/creditdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: credit-processor
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        session.timeout.ms: 30000  # 30 секунд
        heartbeat.interval.ms: 10000  # 10 секунд
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

kafka:
  topics:
    credit-applications: credit-applications

rabbitmq:
  queues:
    credit-decisions: credit-decisions

logging:
  level:
    org.apache.kafka: DEBUG